version: "3.5"
services:
  # API Container
  picture-go:
    container_name: picture-go
    build: .
    restart: "no"
    volumes:
      - ".:/go/src/picture-go"
    ports:
      - "5000:5000"
    networks:
      - picture-api
    environment:
      - GO_ENV=development
      - DB_HOST=172.18.0.1
      - DB_USER=root
      - DB_PWD=root
      - DB_DATABASE=picture-data
      - DB_PORT=3307
      - PORT=5000
      - REDIS_HOST=picture-redis
      - REDIS_PORT=6379
      - REDIS_PWD=""
      - PORT_PWD=""
      - JWT_SECRET="uniuniuniuni"

    # For production comment this line
    command: sh -c "npm i -g knex && air -c .air.conf"

  picture-redis:
    container_name: picture-redis
    build: ./redis
    restart: "no"
    volumes:
      - "./redis/data:/data"
    ports:
      - "6001:6379"
    networks:
      - picture-api

  # Database container
  picture-db:
    container_name: picture-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ".mysql:/var/lib/mysql"
    ports:
      - 3307:3306
    networks:
      - picture-api

  # PHP my admin for managing the database
  picture-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: picture-phpmyadmin
    environment:
      - PMA_HOST=picture-db
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_ARBITRARY=1
    restart: "no"
    ports:
      - 8081:80
    volumes:
      - /sessions
    networks:
      - picture-api

networks:
  picture-api:
    driver: bridge
